# This URI must be valid for the machine running the tests
spring.data.mongodb.uri=mongodb://localhost:27017/byteme_test
# This ensures your main application doesn't try to connect to Docker's internal host during the test run
spring.docker.compose.enabled=false

#testing 2.0